### PR TITLE
More superlatives

### PR DESCRIPTION
**Pull request by yhamoudi**
Fix part of https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/56

### CODE REVIEW

**Comment by Ezibenroc** [comment]
I think that "most recent" should be mapped to `Last` and not `First` (we search for the greatest date).

**Comment by yhamoudi** [comment]
perhaps, you change it. anyway, the predicate for `most recent` is not good

**Comment by Ezibenroc** [comment]
Your example ("What is the most expensive car in the World?") works well.

But if I change "expensive" by "recent", it does not work anymore:
```
What is the most recent car in the World?
{
    "type": "intersection", 
    "list": [
        {
            "object": {
                "type": "missing"
            }, 
            "subject": {
                "value": "most", 
                "type": "resource"
            }, 
            "type": "triple", 
            "predicate": {
                "value": "recent car", 
                "type": "resource"
            }
        }, 
        {
            "object": {
                "type": "missing"
            }, 
            "subject": {
                "value": "world", 
                "type": "resource"
            }, 
            "type": "triple", 
            "predicate": {
                "value": "recent car", 
                "type": "resource"
            }
        }
    ]
}
```

**Comment by yhamoudi** [comment]
I think it's a problem from the stanford parser: 
demo

**Comment by yhamoudi** [comment]
there is no link between `recent` and `most` in the tree. It should be (i think): `car -amod-> recent -advmod-> most`

**Comment by Ezibenroc** [comment]
Ok, we really need to train this parser...

Do you agree with the few superlatives I added?

**Comment by yhamoudi** [comment]
> Do you agree with the few superlatives I added?

yes

**Pull request merged**
