### PR TITLE
CoreNLP server, fix #148

### LINKED ISSUE #148: Use the CoreNLP HTTP API
CoreNLP has now an HTTP API. it would be nice to use it in order to have a more modular architecture and avoid the dependence on a CoreNLP Python wrapper.

API doc: https://stanfordnlp.github.io/CoreNLP/corenlp-server.html

### PR DESCRIPTION
**Pull request by Ezibenroc**
**Dependency: https://github.com/ProjetPP/Scripts/pull/7**

These are the required changes to use the [CoreNLP server](http://stanfordnlp.github.io/CoreNLP/corenlp-server.html).

I already explained a bit in #148 what were the main issues. CoreNLP does not use the same dependencies as before, so I needed to adapt some code.
For the moment, I transform these new dependencies into the older ones (see [processForCompatibility](https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/blob/http_corenlp/ppp_questionparsing_grammatical/dependencyTree.py#L318)). The idea is to adapt our algorithms to these new dependencies in the future.

I realized that our "unit tests" are not unit at all, since a lot of them rely on the output of CoreNLP. This is why I had to rewrite nearly entirely the file [data.py](https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/blob/http_corenlp/tests/data.py). A great idea would be to write better tests...

### CODE REVIEW

**Comment by Ezibenroc** [comment]
Note: Travis fails because https://github.com/ProjetPP/Scripts/pull/7 is not yet merged.

**Comment by ProgVal** [comment]
There are some issues after updating `bootstrap_corenlp.sh`: https://travis-ci.org/ProjetPP/PPP-QuestionParsing-Grammatical/jobs/118461688

**Comment by Ezibenroc** [comment]
That's because you copied the wrong version of bootstrap_corenlp.sh in the Deployment repository : https://github.com/ProjetPP/Deployment/commit/477cebcf863c623f9167a9e80576dc560792b9cf

**Comment by ProgVal** [comment]
Could you fix it, please?

**Comment by Ezibenroc** [comment]
Any idea on how to fix java on Travis? It seems to use inconsistent versions for `java` and `javac`.

**Comment by ProgVal** [comment]
nope

**Comment by Tpt** [comment]
It's probably because the build is done with the installed Java 8 and then the run is done with the Java provided by Ubuntu

**Comment by Ezibenroc** [comment]
> All checks have passed

yay

**Comment by ProgVal** [comment]
:tada:

**Pull request merged**
