### PR TITLE
Exist questions

### PR DESCRIPTION
**Pull request by yhamoudi**
Deal with "exists" questions:
  - Is there a ghost in my house
  - Is there a pilot in the plane
  - Is there a capital in France
  - Is there a king of england (@Tpt > problem, wikidata will answer "yes" https://www.wikidata.org/wiki/Q18810062)
  - Are there computers in your room

It's far from being good, but the parsing of most of the "exists" questions fails, or there are problems of grammatical analysis that are not due to the "exists".

### CODE REVIEW

**Comment by Tpt** [comment]
"Is there a king of england" -> Wikidata will answer yes, and I don't think it's a problem as England is a monarchy (even if the monarch is, in fact, a Queen). But it's not the topic of this PR, I believe

**Comment by yhamoudi** [comment]
Perhaps it's a philosophical question (https://uk.answers.yahoo.com/question/index?qid=20100111111007AAfYJwS) but anyway...

**Comment by Ezibenroc** [comment]
It behaves poorly on simple questions:
```
Are there beers in Germany?
{
    "list": {
        "list": [
            {
                "value": "beer", 
                "type": "resource"
            }, 
            {
                "predicate": {
                    "value": "identity", 
                    "type": "resource"
                }, 
                "object": {
                    "type": "missing"
                }, 
                "subject": {
                    "value": "Germany", 
                    "type": "resource"
                }, 
                "type": "triple"
            }
        ], 
        "type": "intersection"
    }, 
    "type": "exists"
}
```
But I think this due to the `dep` dependency in the tree:
tmp
→ We really should train the parser.

**Comment by Ezibenroc** [comment]
We do not handle questions such as "Does a king of England exist?", but we can keep it for another pull request.

**Pull request merged**
