### PR TITLE
NounDB & JSON

### PR DESCRIPTION
**Pull request by Ezibenroc**
See #132 

Allow to load and save in JSON format (in addition of pickle format).

### CODE REVIEW

**Comment by yhamoudi** [comment]
Here it is for `*.txt` format. 

Do we agree to replace `nounificationManual.json` by `nounificationManual.txt` (you can obtain `nounificationManual.txt` just by doing a `n.save(nounificationManual.txt)`) ?

**Comment by yhamoudi** [comment]
And I tried to respect the coding conventions :innocent: I've made a `txt` class (i'm not sure that the name is good, but after we use `json` and `pickle`), i don't know if there is a better way to do.

**Comment by Ezibenroc** [comment]
>Do we agree to replace nounificationManual.json by nounificationManual.txt

Yes.

> i'm not sure that the name is good

No we should choose a better name, which begins by a capital letter. `TextIO`?

**Comment by yhamoudi** [comment]
`TextStream` ?

**Comment by Ezibenroc** [comment]
This is not a stream :)

**Comment by yhamoudi** [comment]
it's I/O streams.

**Comment by Ezibenroc** [comment]
You can merge if you are ok.

**Pull request merged**
