### PR TITLE
Travis and stanford

### PR DESCRIPTION
**Pull request by Ezibenroc**
Make travis run the global tests, for a better code coverage.
This imply to automatically download  and install the `Stanford Parser` and the `corenlp` wrapper.

### CODE REVIEW

**Comment by Ezibenroc** [comment]
There is an annoying bug with travis:
```
[nltk_data] Error downloading 'wordnet' from <http://www.nltk.org/nltk
[nltk_data]     _data/packages/corpora/wordnet.zip>:   [Errno 104]
[nltk_data]     Connection reset by peer
Error installing package. Retry? [n/y/e]
```

The bug appeared once in `Pypy 3` and once in `Python 3.2`. The installation has also been successful once for both of these.

We need to fix this before merging the pull request.

**Comment by Ezibenroc** [comment]
@ProgVal, any clue?

**Comment by ProgVal** [comment]
echo "yyy" | whatever command you run to install nltk data

**Comment by Ezibenroc** [comment]
I thought about that, but I was sure that you would not like it :)

**Comment by ProgVal** [comment]
I'm sure I have that kind of loop somewhere in the PPP.

**Comment by ProgVal** [comment]
Er, actually I meant:
```
echo "y
y
y
" | python -m nltk.downloader wordnet

(I think it needs a new line character to take it into account)

**Comment by Ezibenroc** [comment]
Fixed. Is it ok now?

**Pull request merged**
