### PR TITLE
More concise tests.

### PR DESCRIPTION
**Pull request by ProgVal**

### CODE REVIEW

**Comment by Ezibenroc** [comment]
Please make sure that the tests run successfuly when you open a pull request.
For this, you should run `./run_deep_tests.py`, with a Stanford CoreNLP server in background.

**Comment by Ezibenroc** [comment]
But thank you for the idea of conciseness.

**Comment by ProgVal** [comment]
Sorry, I did not feel like downloading the Stanford Parser with a 100KB/s bandwidth

**Comment by ProgVal** [comment]
By the way, could you make Travis run the deep tests?

**Comment by Ezibenroc** [comment]
> Sorry, I did not feel like downloading the Stanford Parser with a 100KB/s bandwidth

and

> By the way, could you make Travis run the deep tests?

Do you feel the contradiction? :smiley:

It would take a very long time on travis at each time.
Moreover, we might replace NLTK by [ConceptNet](http://conceptnet5.media.mit.edu/) which has a 5GB database, so the travis time would be even longer...

**Comment by ProgVal** [comment]
Then only push in the morning, Travis has a 13MB/s download speed when it's night in the US :)

**Pull request merged**
