### PR TITLE
Better quotation handling.

### PR DESCRIPTION
**Pull request by Ezibenroc**
Use a regexp to handle quotations.

Before, any ugly quotation was recognized (for instance “foo“, with an openning quotation mark to close the quotation). Now we only recognize quotations with a correct syntax.

This allows quotations marks within a quotation (like in python).

### CODE REVIEW

**Comment by Ezibenroc** [comment]
This PR also fix the build error which apparently also exist in branch master. It seems that there has ben a renaming of the Stanford library (`stanford-corenlp-full-2015-01-30` → `stanford-corenlp-full-2015-01-29`).

**Comment by Ezibenroc** [comment]
@yhamoudi Merge?

**Comment by yhamoudi** [comment]
i'm not sure i understand everything, but it seems good

**Comment by Ezibenroc** [comment]
The algorithm is the same: replace each quotation by some unique string, and store these substitutions in a map.

The only change is the way we find the quotations. Before it was an ugly traversal algorithm. Now, we use regular expressions.

**Pull request merged**
